language: julia

julia:
  - release
  - nightly

script:
  - julia -e 'Pkg.init(); Pkg.clone("https://github.com/adityam/MDP.jl"); Pkg.test("MDP", coverage=true)'

after_success:
- julia -e 'cd(Pkg.dir("MDP")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
