language: julia
os:
  - linux
  - osx
julia:
  - 1.1
  - nightly

script:
  - julia -e 'using Pkg; Pkg.activate("."); Pkg.instantiate(); Pkg.test("MDP", coverage=true)'

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'

coveralls: true
  
matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true
